import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowLeft, ArrowRight, Heart, Mail, Sparkles, X, Camera, Volume2, VolumeX, Utensils, RotateCcw } from 'lucide-react';
import confetti from 'canvas-confetti';
import { content } from './content';
import { birthdayMusic } from './birthdayMusic';
import './style.css';
import './scrapbook.css';

const files = import.meta.glob('/public/photos/*.{jpg,jpeg,png,webp,avif,JPG,JPEG,PNG,WEBP}', { eager: true, query: '?url', import: 'default' });
const uploadedPhotos = Object.keys(files).sort((a,b) => a.localeCompare(b, undefined, { numeric: true })).slice(0,20).map(path => path.replace('/public', ''));
const demoPhotos = ['1490750967868-88aa4486c946', '1511988617509-a57c8a288659', '1518621736915-f3b1c41bfd00', '1470252649378-9c29740c9fa8', '1464822759023-fed622ff2c3b', '1500530855697-b586d89ba3ee'].map(id => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`);
const photos = uploadedPhotos.length ? uploadedPhotos : demoPhotos;
function celebrate() { if (!matchMedia('(prefers-reduced-motion: reduce)').matches) void confetti({ particleCount: 110, spread: 85, origin: { y: .7 }, colors: ['#bd244a','#f6a6bd','#e7bd62','#ffffff'] }); }
function App() {
 const [intro,setIntro] = useState<number|null>(4);
 const [now,setNow] = useState(Date.now());
 const [letter,setLetter] = useState(false);
 const [view,setView] = useState<number|null>(null);
 const [reason,setReason] = useState(0);
 const [wish,setWish] = useState(false);
 const [cut,setCut] = useState(false);
 const [heartTaps,setHeartTaps] = useState(0);
 const [playing,setPlaying] = useState(false);
 const left = Math.max(0,new Date(content.birthday).getTime()-now);
 const units = [Math.floor(left/86400000),Math.floor(left/3600000)%24,Math.floor(left/60000)%60,Math.floor(left/1000)%60];
 useEffect(() => {const timer=setInterval(()=>setNow(Date.now()),1000);return ()=>clearInterval(timer)},[]);
 useEffect(() => {
  if(intro===null || intro===4)return;
  const timer=setTimeout(()=>{if(intro===1){setIntro(null);window.scrollTo(0,0);celebrate()}else setIntro(intro-1)},intro===4?2400:1000);
  return ()=>clearTimeout(timer);
 },[intro]);
 useEffect(()=>{if(intro===null)return;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=''}},[intro]);
 useEffect(()=>{if(intro===null)document.querySelector<HTMLElement>('.hero .primary')?.focus({preventScroll:true})},[intro]);
 useEffect(()=>{if(!letter && view===null)return; const previous=document.activeElement as HTMLElement; document.body.style.overflow='hidden'; const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setLetter(false);setView(null)}; if(view!==null && e.key==='ArrowRight')setView((view+1)%photos.length); if(view!==null && e.key==='ArrowLeft')setView((view-1+photos.length)%photos.length); if(e.key==='Tab'){const items=Array.from(document.querySelectorAll<HTMLElement>('.modal button'));const first=items[0],last=items[items.length-1];if(e.shiftKey && document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey && document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',close);document.querySelector<HTMLElement>('.modal button')?.focus();return()=>{document.body.style.overflow='';document.removeEventListener('keydown',close);previous?.focus()}},[letter,view]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 async function startMusic(){try{await birthdayMusic.play();setPlaying(true)}catch{setPlaying(false)}}
 async function toggleMusic(){if(playing){birthdayMusic.pause();setPlaying(false)}else await startMusic()}
 function openSurprise(){void startMusic();setIntro(3)}
 function nextReason(){setReason((reason+1)%content.reasons.length);setHeartTaps(heartTaps+1);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)navigator.vibrate?.(35)}
 function cakeAction(){if(!wish){setWish(true);celebrate()}else if(!cut){setCut(true);celebrate()}}
 function resetCake(){setWish(false);setCut(false)}
 return <>{intro!==null&&<div className="surprise-intro" role="dialog" aria-modal="true" aria-label="Your birthday surprise"><div className="intro-heart"><Heart size={40} fill="currentColor"/></div><p className="eyebrow">FOR MY KUCHU PUCHU</p><h2>Now, here is the surprise<br/>I was talking about.</h2><div className="intro-count" aria-live="polite" aria-atomic="true">{intro===4?<span className="handwritten">A little world, made just for you...</span>:<strong key={intro}>{intro}</strong>}</div><p className="handwritten">with love, your Gublu ♡</p>{intro===4?<button autoFocus className="text-button" onClick={openSurprise}>Open my surprise <ArrowRight size={16}/></button>:<button className="text-button" onClick={()=>{setIntro(null);window.scrollTo(0,0)}}>Skip countdown <ArrowRight size={16}/></button>}</div>}<div inert={intro!==null}><header><a href="#home" className="brand" aria-label="Back to top">s<span>♡</span></a><span>A LITTLE WORLD, JUST FOR YOU</span><button className="icon" onClick={toggleMusic} aria-label={playing?'Pause music':'Play music'} title={playing?'Pause music':'Play music'} aria-pressed={playing}>{playing?<Volume2 size={19}/>:<VolumeX size={19}/>}</button></header>
 <main><section id="home" className="hero"><div className="hero-photo"><img src={photos[0] || 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1600&q=85'} alt={photos[0]?`${content.name}, my favourite person`:'Delicate spring flowers'} /></div><div className="hero-copy"><p className="eyebrow"><span/> OCTOBER 23 · YOUR DAY</p><h1>Happy birthday,<br/><em>{content.name}.</em></h1><p className="intro">My Swarnali. My Puchku.<br/>You make my world a little more beautiful.</p><a className="primary" href="#memories">A little something for you <ArrowDown size={17}/></a><span className="handwritten">made with all my love ♡</span></div><div className="hero-bottom"><span>OUR NEXT LITTLE CELEBRATION</span><a href="#countdown" aria-label="Scroll to birthday countdown"><ArrowDown size={18}/></a></div></section>
 <section id="countdown" className="countdown reveal"><p className="eyebrow">{left>0?'COUNTING THE MOMENTS':'TODAY & ALWAYS'}</p><h2>{left>0?'Until the world gets to celebrate you.':'The world is sweeter with you in it.'}</h2>{left>0?<div className="clock">{units.map((value,i)=><div key={i}><strong>{String(value).padStart(2,'0')}</strong><span>{['days','hours','minutes','seconds'][i]}</span></div>)}</div>:<p className="birthday-message">Happy birthday, my love. This little world is yours forever.</p>}<p className="small">23 October 2026 <span>♡</span> A date worth circling</p></section>
 <section id="memories" className="memories scrapbook"><div className="section-heading reveal"><div><p className="eyebrow">THE LITTLE THINGS, THE BIG FEELINGS</p><h2>Our kind of <em>magic.</em></h2></div><p>Some moments deserve<br/>to be kept forever.</p></div>{Array.from({length:Math.ceil(photos.length/6)},(_,chapter)=><div className="scrapbook-page" key={chapter}><div className="scrapbook-chapter"><span>CHAPTER {String(chapter+1).padStart(2,'0')}</span><span>{['little moments, big love','more of us, please','the story keeps getting sweeter','always my favourite'][chapter]}</span></div><div className="photo-grid"><div className="margin-note"><span className="handwritten">{['If I could keep a feeling,\nit would be this one.','Somehow, every road\nleads back to you.','My favourite story\nis still us.','More memories.\nMore you. More us.'][chapter]}</span><Heart size={26} strokeWidth={1.2}/><span className="note-arrow" aria-hidden="true">↙</span></div>{photos.slice(chapter*6,chapter*6+6).map((src,slot)=>{const i=chapter*6+slot;return <button className={`polaroid memory-${slot+1}`} key={src} onClick={()=>setView(i)} aria-label={`Open memory ${i+1}: ${content.captions[i]}`}><span className="photo-tape" aria-hidden="true"/><span className="memory-image"><img src={src} alt={content.captions[i]} loading="lazy"/><span className="memory-peek" aria-hidden="true"><Heart size={20}/></span></span><span className="memory-caption">{content.captions[i]}</span><small>{String(i+1).padStart(2,'0')} / A PIECE OF MY HEART</small>{slot===0&&<span className="photo-stamp" aria-hidden="true">favourite<br/>♡</span>}</button>})}<div className="scrapbook-aside"><span className="handwritten">a little proof that<br/>happiness looks like us.</span><span className="keepsake-mark" aria-hidden="true"><Heart size={18}/></span></div></div></div>)}<p className="handwritten gallery-end">and so many more memories to make...</p></section>
 <section className="love-notes reveal"><p className="eyebrow">IN CASE YOU EVER FORGET</p><h2>A few things I <em>love about you.</em></h2><div className="reason"><span className="reason-number">{String(reason+1).padStart(2,'0')}</span><Heart size={24}/><p key={reason} aria-live="polite">{content.reasons[reason]}</p><button className="heart-button" aria-label="One more reason" title="One more reason" onClick={nextReason}><Heart key={heartTaps} size={32} fill="currentColor" className={heartTaps?'heart-pop':''}/>{heartTaps>0&&<span key={`burst-${heartTaps}`} className="heart-burst" aria-hidden="true">{[0,1,2,3,4,5].map(i=><Heart key={i} size={12} fill="currentColor" style={{'--i':i} as React.CSSProperties}/>)}</span>}</button></div><span className="small">{reason+1} of {content.reasons.length} little reminders</span></section>
 <section className="letter-section reveal"><div className="envelope" aria-hidden="true"><Mail size={72} strokeWidth={1}/><span>for you, always</span><Heart size={20} fill="currentColor"/></div><div><p className="eyebrow">FROM MY HEART TO YOURS</p><h2>Some words,<br/><em>just for you.</em></h2><p>Because the best things are sometimes<br/>the hardest to put into words.</p><button className="primary" onClick={()=>setLetter(true)}>Open your letter <Mail size={17}/></button></div></section>
 <section className="wish-section reveal"><p className="eyebrow">ONE LAST LITTLE THING</p><h2 aria-live="polite">{cut?'The first slice is always yours, Puchku.':wish?'May every wish find its way to you.':'Close your eyes. Make a wish.'}</h2><button className={`cake ${wish?'blown':''} ${cut?'cut':''}`} aria-label={cut?'Celebrate again':wish?'Cut the birthday cake':'Blow out the birthday candle'} onClick={()=>{if(cut)resetCake();else cakeAction()}}><span className="flame"/><span className="candle"/><span className="icing"/><span className="cake-body"><Heart size={25} fill="currentColor"/></span><span className="cake-slice"><span className="slice-icing"/><Heart size={15} fill="currentColor"/></span><span className="cake-knife"/><span className="plate"/></button><p>{cut?'A little sweetness for my sweetest person.':wish?'And now, a slice of birthday happiness.':'A little birthday magic, just for you.'}</p>{!cut&&<button className="text-button" onClick={cakeAction}>{wish?'Cut the cake':'Blow out the candle'} {wish?<Utensils size={16}/>:<Sparkles size={16}/>}</button>}{wish&&<button className="text-button" onClick={resetCake}>{cut?'Celebrate again':'Make another wish'} <RotateCcw size={16}/></button>}</section>
 </main><footer><Heart size={18} fill="currentColor"/><p>For {content.name}. With love. Always.</p><span>Made by {content.from}</span><a href="#home">Back to the beginning <ArrowLeft size={13}/></a></footer>
 {letter&&<div className="overlay" onClick={()=>setLetter(false)}><div className="modal letter-modal" role="dialog" aria-modal="true" aria-label="Your birthday letter" onClick={e=>e.stopPropagation()}><button className="close icon" aria-label="Close letter" onClick={()=>setLetter(false)}><X/></button><p className="eyebrow">A LETTER FOR YOU</p><h2>My dearest {content.name},</h2>{content.letter.map((p,i)=><p key={i}>{p}</p>)}<p className="handwritten">All my love,<br/>{content.from} ♡</p></div></div>}
 {view!==null&&<div className="overlay" onClick={()=>setView(null)}><div className="modal photo-modal" role="dialog" aria-modal="true" aria-label="Photo memory" onClick={e=>e.stopPropagation()}><button className="close icon" aria-label="Close photo" onClick={()=>setView(null)}><X/></button><img src={photos[view]} alt={content.captions[view]}/><p className="handwritten">{content.captions[view]}</p><div className="photo-controls"><button className="icon" aria-label="Previous photo" onClick={()=>setView((view-1+photos.length)%photos.length)}><ArrowLeft/></button><span>{view+1} / {photos.length}</span><button className="icon" aria-label="Next photo" onClick={()=>setView((view+1)%photos.length)}><ArrowRight/></button></div></div></div>}
 </div></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
